# Generated by Django 4.0.5 on 2022-06-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrank',
            name='attempt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userrank',
            name='correct_answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userrank',
            name='quiz_passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userrank',
            name='total_time',
            field=models.IntegerField(default=0),
        ),
    ]
