# Generated by Django 4.0.5 on 2022-06-21 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userrank_attemp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrank',
            old_name='attemp',
            new_name='attempt',
        ),
    ]
